New openturns.memoryview extension module
With this commit, a new openturns.memoryview extension module is added.
It provides a Buffer class which supports Python protocol buffer
(aka PEP 3118); with this class, we can wrap OT data containers into
Python objects without copy, as is done for instance in numpy.

Commit 65cc96a allowed to efficiently copy Python buffers into OT
Sample, so conversion between OT and Python should now be quite fast.

The Buffer class supports indexing (but not slicing for the moment),
but nothing more.  To use this class for numerical computations, it
must be passed to a Point or Sample (which makes a copy), or numpy
(with or without copy).

This example illustrates these capabilities; there is no reason for
users or developers to use this Buffer class as in this example, it
should only be used by SWIG to wrap OT containers into Python objects.

  >>> from __future__ import print_function
  >>> import openturns as ot
  >>> import openturns.memoryview
  >>> import numpy as np
  >>> ot.RandomGenerator.SetSeed(0)
  >>> s = ot.Normal(4).getSample(2)
  >>> print(s)
      [ X0        X1        X2        X3        ]
  0 : [  0.608202 -1.26617  -0.438266  1.20548  ]
  1 : [ -2.18139   0.350042 -0.355007  1.43725  ]
  # Constructor takes 2 tuples as arguments:
  #   * First tuple contains memory  address, and a boolean telling if Buffer
  #     owns this memory (with a copy) or not.
  #   * Second tuple contains array dimensions
  >>> x = openturns.memoryview.Buffer((int(s.__baseaddress__()), False), (s.getSize(), s.getDimension()))
  >>> print(x)
  <read-only buffer at 0x559e4a456b20 shape=(2,4)>
  # Indexing returns a new Buffer, without copy
  >>> print(x[0])
  <read-only buffer at 0x559e4a456b20 shape=(4)>
  >>> print(x[1])
  <read-only buffer at 0x559e4a456b40 shape=(4)>
  <read-only buffer at 0x1594460 shape=(4)>
  # A 0-d Buffer is a scalar
  >>> print(x[1][0])
  -2.18138523462
  #  Buffer is read-only
  >>> x[1][0] = 3
  TypeError: 'openturns.memoryview.Buffer' object does not support item assignment
  >>> for p in x:
  ...     print([q for q in p])
  [0.6082016512187646, -1.2661731022166567, -0.43826561996041397, 1.2054782008285756]
  [-2.1813852346165143, 0.3500420865302907, -0.3550070491856397, 1.437249310140903]
  # Copy into a Sample; our SWIG bindings have been taught recently to use Python
  # buffer protocol, so this is fast.
  >>> y = ot.Sample(x)
  >>> print(y)
  0 : [  0.608202 -1.26617  -0.438266  1.20548  ]
  1 : [ -2.18139   0.350042 -0.355007  1.43725  ]
  >>> y == s
  True
  # But numpy also allows to wrap this object into an array without copy
  >>> z = np.array(x, copy=False)
  >>> z.__array_interface__
  {'descr': [('', '<f8')], 'strides': None, 'shape': (2, 4), 'version': 3, 'typestr': '<f8', 'data': (94138339257120, True)}
  >>> hex(94138339257120)
  '0x559e4a456b20'
  # Reverse indexing operation, this may be useful when a PythonFunction
  # defines _exec_sample but not _exec; looping may then be done in C
  # instead of Python, and without copy.  But as Point does not define
  # __baseaddress__(), we cannot build a Buffer directly from a Point in
  # Python, but this is possible in C.  Let us slice a Sample:
  >>> x1 = x[1]
  >>> print(x1)
  <read-only buffer at 0x559e4a456b40 shape=(4)>
  >>> s1 = x1.augment()
  >>> print(s1)
  <read-only buffer at 0x559e4a456b40 shape=(1,4)>
  # s1 is a 2d container which can be passed to _exec_sample
  >>> print(ot.Sample(s1))
  0 : [ -2.18139   0.350042 -0.355007  1.43725  ]
  # Alternatively, define a Buffer from a Sample with only one
  # dimension; 2nd argument is a tuple, do not forget the comma!
  >>> x0 = openturns.memoryview.Buffer((int(s.__baseaddress__()), False), (s.getSize(),))